### ISSUE TITLE
python3.5 not support iteritems

### ISSUE THREAD

**Issue by zodman** [amonapp/amon#153]
```
ERROR Internal Server Error: /api/system/APIKEY
Traceback (most recent call last):
  File "/export/web/amon.interalia.net/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/export/web/amon.interalia.net/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/export/web/amon.interalia.net/env/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/export/web/amon.interalia.net/env/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/export/web/amon.interalia.net/env/lib/python3.5/site-packages/rest_framework/views.py", line 477, in dispatch
    response = self.handle_exception(exc)
  File "/export/web/amon.interalia.net/env/lib/python3.5/site-packages/rest_framework/views.py", line 437, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/export/web/amon.interalia.net/env/lib/python3.5/site-packages/rest_framework/views.py", line 474, in dispatch
    response = handler(request, *args, **kwargs)
  File "/export/web/amon.interalia.net/amon/amon/apps/api/views/core.py", line 95, in post
    api_model.save_data_to_backend(server=request.server, data=data)
  File "/export/web/amon.interalia.net/amon/amon/apps/api/models.py", line 52, in save_data_to_backend
    for name, d in formated_data.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'

```

**Comment by martinrusev** [comment]
@zodman Fixed right here: https://github.com/amonapp/amon/commit/b358956f73675a3a4b28ff6752ba4193786889ed#diff-974c6027db797e501288ad1d2653b1fcL52
