### ISSUE TITLE
Installation Instructions currently lead to failure

### ISSUE THREAD

**Issue by docdawning** [amonapp/amon#169]
I've just setup a fresh Ubuntu 16.04 VM. I've then followed the instructions here exactly: https://docs.amon.cx/onpremise/#install

amon will not run for me, I get output such as:
```
(env) root@amon:/opt/amon# python manage.py migrate 
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/amon/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/opt/amon/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 307, in execute
    settings.INSTALLED_APPS
  File "/opt/amon/env/lib/python3.5/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/opt/amon/env/lib/python3.5/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/amon/env/lib/python3.5/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/opt/amon/amon/settings.py", line 242, in <module>
    EMAIL_USE_TLS = smtp.get('use_tls', False)
AttributeError: 'bool' object has no attribute 'get'
```
I suspect I'm missing some dependency. That should be added to the installation instructions, please.

**Comment by djsakisd** [comment]
Hi @docdawning i came across this issue and solved it byt creating the file "/etc/opt/amon.yml" with your data .. look in the installation instructions there is one example.

**Comment by docdawning** [comment]
Thanks @djsakisd, I followed the instructions step asking for: `touch /etc/opt/amon/amon.yml`, which is not `touch /etc/opt/amon.yml`. I removed the empty file I was instructed to create and instead symlinked over that from my git environment: `ln -s /opt/amon/amon.yml /etc/opt/amon/`. Upon doing this, the migrate function seemed to execute fine.

**Comment by djsakisd** [comment]
@docdawning sorry i typed wrong dir , its   /etc/opt/amon/amon.yml. glad it worked and u fixed the problem.
