### ISSUE TITLE
Alert history 500 errors

### ISSUE THREAD

**Issue by ashleyhindle** [amonapp/amon#193]
When clicking the link to view an alerts history we instead receive an error:

* Link clicked, from `/alerts/`
![clicking-link](https://i.ashleyhindle.com/2017-11-29_13-17-47-y0mhzr6b62.png)

* Error, from `/alerts/history/system/5a1d4d3bc323c9063c35e1d9/`
![alert-history-error](https://i.ashleyhindle.com/2017-11-29_13-18-07-hreyuez8v9.png)

# Logs:

`==> amonapp.log <==`

```
[29/Nov/2017 13:13:30] ERROR [django.request:135] Internal Server Error: /alerts/history/system/5a1d4d3bc323c9063c35e1d9/
Traceback (most recent call last):
  File "/opt/amon/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/opt/amon/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/opt/amon/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/amon/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/amon/env/lib/python3.5/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/amon/amon/apps/alerts/views/alerts.py", line 222, in history_system
    total_pages = range(total_pages)
TypeError: 'float' object cannot be interpreted as an integer
```

`==> amon_requests.log <==`

```
ERROR Internal Server Error: /alerts/history/system/5a1d4d3bc323c9063c35e1d9/
Traceback (most recent call last):
  File "/opt/amon/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/opt/amon/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/opt/amon/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/amon/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/amon/env/lib/python3.5/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/amon/amon/apps/alerts/views/alerts.py", line 222, in history_system
    total_pages = range(total_pages)
TypeError: 'float' object cannot be interpreted as an integer
```

**Comment by ashleyhindle** [comment]
Looking at line 222 `/opt/amon/amon/apps/alerts/views/alerts.py` shows: `total_pages = range(total_pages)`

Surrounding code:
```
    total = alerts_history_model.count_notifications(alert_id=alert['_id'])

    on_page = 100
    if total > on_page:
        total_pages = total/on_page
    else:
        total_pages = 1

    total_pages = range(total_pages)
```

If we change the division to double slashes `//` it returns an int, and the range call succeeds and the page loads as expected
